apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: togglemaster
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flag-service
  labels:
    app.kubernetes.io/name: flag-service
    app.kubernetes.io/part-of: togglemaster
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: targeting-service
  labels:
    app.kubernetes.io/name: targeting-service
    app.kubernetes.io/part-of: togglemaster
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: evaluation-service
  labels:
    app.kubernetes.io/name: evaluation-service
    app.kubernetes.io/part-of: togglemaster
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  labels:
    app.kubernetes.io/name: analytics-service
    app.kubernetes.io/part-of: togglemaster
automountServiceAccountToken: false
